<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;
use Doctrine\DBAL\LockMode;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
}
