# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    user.service:
        class: AppBundle\Service\UserService
        arguments: ['@doctrine.orm.entity_manager']
